spring:
  application:
    name: springfox-swagger
server:
  port: 8989

# ===== swagger ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0 Demo
  try-host: http://localhost:${server.port}
